name: main
version: '${project.version}'
main: fantasykingdom.fkd.Main
api-version: 1.19
commands:
  gui:
    description: opens the gui
  fly:
    description: enables fly
    usage: /<command>
  flyspeed:
    description:  set your flyspeed
    usage: /commannd <speed>